### ISSUE TITLE
Change input/output data model for predict requests

### ISSUE THREAD

**Issue by MLnick** [IBM/MAX-News-Text-Generator#16]
I noticed while looking at #14 that the response format is a bit odd for this model: it returns a list of `{"pred_text":...}` objects. But there is only one predicted text string that will be returned.

I suggest changing the output format to something similar to https://github.com/IBM/MAX-Review-Text-Generator. While doing that we could also update the input style to take a JSON object `{"seed_text":...}` like the review generator.

**Comment by bdwyer2** [comment]
@MLnick yep, looks like I did the same thing for the audio embedding generator. I will fix that one as well with https://github.com/IBM/MAX-Audio-Embedding-Generator/pull/15
