### ISSUE TITLE
Missing link to model files

### ISSUE THREAD

**Issue by vabarbosa** [IBM/MAX-News-Text-Generator#3]
The [README.md](https://github.com/IBM/MAX-News-Text-Generator/blob/master/README.md) states the following:

> The model files are hosted on IBM Cloud Object Storage

However, there is no link provided to the model files in IBM Cloud Object Storage.
Some of the other [IBM MAX models](https://developer.ibm.com/code/exchanges/models/) do contain direct links to download the model
files but I do see the link in this model.

**Comment by bdwyer2** [comment]
Hi vabarbosa, the links are contained in the docker file. There is no reason for end users to download the weights themselves.

**Comment by ptitzler** [comment]
What's the standard for MAX assets? Include links to the file location or not? We need to be consistent. If there's no reason for users to download the files the readme should not contain the text _The model files are hosted on IBM Cloud Object Storage_ statement because it doesn't provide any value to the user.

**Comment by bdwyer2** [comment]
@vabarbosa do you have any more thoughts? If not do you mind if I close this issue?

**Comment by vabarbosa** [comment]
@bdwyer2 i would agree with the statement from @ptitzler. there should be consistency.

some models (e.g., [Image Colorizer](https://github.com/IBM/MAX-Image-Colorizer), [Inception ResNet V2](https://github.com/IBM/MAX-Inception-ResNet-v2)) do include the link to the model files in the README while others (this one, [Audio Embedding Generator](https://github.com/IBM/MAX-Audio-Embedding-Generator)) do not.

i would prefer all include the link to the model files in the README. however, if there is a legitimate reason this shouldn't be done then as ptitzler said:

> the readme should not contain the text _The model files are hosted on IBM Cloud Object Storage statement_ because it doesn't provide any value
